# Generated by Django 3.2.15 on 2023-01-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('sale', models.PositiveIntegerField(verbose_name='할인 가격')),
                ('stock', models.PositiveIntegerField(verbose_name='재고')),
                ('post', models.TextField(verbose_name='글')),
                ('created', models.DateField(verbose_name='생성날짜')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productimg', verbose_name='제품 사진')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '상품',
                'db_table': 'product',
            },
        ),
    ]
