# Generated by Django 3.2.15 on 2023-01-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimg',
            options={'verbose_name': '제품 이미지', 'verbose_name_plural': '제품 이미지'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': '제품', 'verbose_name_plural': '제품'},
        ),
        migrations.AlterModelTable(
            name='productimg',
            table='productImage',
        ),
    ]
