# Generated by Django 3.2.15 on 2023-01-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20230128_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=models.ManyToManyField(to='product.ProductImg'),
        ),
    ]
